### ISSUE TITLE
Application name in `pg_stat_activity`

### ISSUE THREAD

**Issue by rcknr** [veegres/ivory#451]
I have been using Ivory for the last few weeks and it has been a great addition to my set of tools!
One small thing I wish it had is to declare an application name when connecting to PostgreSQL server, so I can quickly distinguish its queries visually.

**Comment by anselvo** [comment]
Hi, thanks for your feedback.
Just to clarify you would like to see Ivory requests in `pg_stat_activity` and distinguish it by application name right? 
I think this is a great idea and it should be simple, I will try to add it.

**Comment by rcknr** [comment]
That's right! Thanks!

**Comment by ikss** [comment]
Hi @rcknr, until it's not implemented via configuration you can solve it by adding `PGAPPNAME` ENV variable to `docker run` command, like this

`docker run --env PGAPPNAME=Ivory ...`

And this application name will be used for Ivory queries

**Comment by anselvo** [comment]
It's going to be released under 1.3.1

**Comment by rcknr** [comment]
Great, thanks!

**Comment by anselvo** [comment]
yeah I agree, will do it someday :)
