### ISSUE TITLE
Make instance names as same as patroni.name

### ISSUE THREAD

**Issue by dodo920306** [veegres/ivory#513]
**Is your feature request related to a problem? Please describe.**
Please consider make instance names as same as the real patroni.name in the json returned from the REST api since it will make a switchover/failover of instances with names different from their IPs possible.

A mismatch between instance IPs and instance names in Patroni will cause a 412 error when trying to make a switchover/failover since the provided name is different from the real name of the leader.

**Describe the solution you'd like**
Provide the real name of the leader instance in the requests of switchover/failover.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/user-attachments/assets/d160aaa4-1aa8-45fb-bb13-42ab8cd5473f)

**Comment by anselvo** [comment]
Hello!

Thanks for your request. Can you clarify a bit, because I don't understand how it possible, if your name doesn't match patroni name Ivory cannot understand that this is a part of the cluster.

**Comment by anselvo** [comment]
I've fixed the problem with switchover and failover, but I don't want to use patroni.name in all places for displaying it. Maybe it will be change in future. Let me know how frustrating this is for you.

**Comment by dodo920306** [comment]
It's not frustrating at all. I tried deploying the latest version, and it's currently working well. Thanks for the quick fix and update.
